# IDはユニークな文字列であれば何でも良いが、なるべくこの形式で（たぶん並べ替えやすいので）
qid = "q00000206"

# タグは文字列の配列。なしでもよい。
# タグには言語の区別はなくても良いだろう。
tags = [
  "window-function", "aggregation"
]

# カテゴリは必ず１つの文字列。問題の分類に用いる
# 使用できるカテゴリ一覧は別途用意する
# 現在想定しているものは以下（これに含まれないものをアプリ上で表示されないようになっているので、別途アプリ側で追加する必要がある）
#  ja: ("SQL/Teradata 基礎", "SQL/Teradata 中級", "地理空間情報の分析", "時系列情報の分析")
#  en: ("SQL/Teradata Basic", "SQL/Teradata Intermediate", "Geospatial Information Analysis", "Time-series Data")
[category]
ja = "SQL/Teradata 中級"
en = "SQL/Teradata Intermediate"

[title]
ja = """平均給与との差額計算"""
en = """Salary difference from the average"""

[content]
ja = """<em>Terashirt.employee</em> テーブルには、Terashirtの従業員の給与データが含まれています。
全体の給与平均と役職ごとの給与平均を算出し、各従業員ごとに全体の給与平均との差額および役職ごとの給与平均との差額を算出してください。"""
en = """The <em>Terashirt.employee</em> table contains salary data for Terashirt employees.
Calculate the overall salary average and the salary average per position, and for each employee calculate the difference from the overall salary average and the difference from the salary average per position."""

# ヒントが不要なら空文字列にする
[hint]
ja = ""
en = ""

# 参考文献、ウェブサイト (HTMLコードを直接書く)
# 不要なら空文字列にする
[references]
ja = ""
en = ""

# 正誤判定に関する定義
[judgement]
check_shape = true  # クエリ結果の行列数の一致を求めるか
shape = [15, 7]      # 想定されたクエリ結果のサイズ

check_type = false         # クエリ結果の列の型の一致を求めるか
types = [ "int", "str" ]   # 想定されたクエリ結果の変数型

check_value = true  # 想定解との値の一致を求めるか
ordered = false     # クエリ結果の並び順が指定されているかどうか
value_from = "query"  # 想定結果の指定方法
                    # csv      : 想定結果のCSV文字列を指定
                    # query    : 想定結果を生成するクエリを指定。動的に実行して判定する

query = """
select
  last_name || ' ' || first_name AS name
  ,"role"
  ,salary
  ,avg(salary) over() as "全体給与平均"
  ,avg(salary) over(partition by "role") as "roleごと給与平均"
  ,salary - "全体給与平均" as "全体給与平均との差額"
  ,salary - "roleごと給与平均" as "roleごと給与平均との差額"
from TeraShirt.employee
order by 6,7;
"""

check_explain = false   # クエリのExplain結果に関する条件を課すか
explain_should_include = []      # Explanation が含むべきキーワードのリスト
explain_should_not_include = []  # Explanation が含んではいけないキーワードのリスト