# IDはユニークな文字列であれば何でも良いが、なるべくこの形式で（たぶん並べ替えやすいので）
qid = "q00000205"

# タグは文字列の配列。なしでもよい。
# タグには言語の区別はなくても良いだろう。
tags = [
  "window-function"
]

# カテゴリは必ず１つの文字列。問題の分類に用いる
# 使用できるカテゴリ一覧は別途用意する
# 現在想定しているものは以下（これに含まれないものをアプリ上で表示されないようになっているので、別途アプリ側で追加する必要がある）
#  ja: ("SQL/Teradata 基礎", "SQL/Teradata 中級", "地理空間情報の分析", "時系列情報の分析")
#  en: ("SQL/Teradata Basic", "SQL/Teradata Intermediate", "Geospatial Information Analysis", "Time-series Data")
[category]
ja = "SQL/Teradata 中級"
en = "SQL/Teradata Intermediate"

[title]
ja = """最初のお客様"""
en = """First customer"""

[content]
ja = """TeraShirt社の各店舗について、１番最初に商品を購入した顧客を探して、店舗名、購入日時、顧客名（姓名を半角スペースでつなげたもの）を表示してくださいとしてください。
便宜上、顧客名が不明の売上レコードは除いて考えてください。
また、同じ店舗で全く同じ日時に複数の顧客による購入があった場合、そのすべてを表示してください。
"""
en = """For each store of the TeraShirt Company, fund the first customer who made a purchase in it.
Display the store name, purchase datetime, and the customer name (last name and first name with a space inbetween).
For the convenience, ignore the records where the customer name is missing.
If there are multiple more than one customers who made purchases at the same store and exactly the same time, then show them all.
"""

# ヒントが不要なら空文字列にする
[hint]
ja = """
<ul>
<li><a href="https://docs.teradata.com/r/Teradata-VantageTM-SQL%E9%96%A2%E6%95%B0-%E5%BC%8F-%E3%81%8A%E3%82%88%E3%81%B2%E8%BF%B0%E9%83%A8-17.20/%E9%A0%86%E5%BA%8F%E4%BB%98%E3%81%8D%E5%88%86%E6%9E%90%E9%96%A2%E6%95%B0/%E3%82%A6%E3%82%A3%E3%83%B3%E3%83%88%E3%82%A6%E9%9B%86%E7%B4%84%E9%96%A2%E6%95%B0/ROW_NUMBER" rel="noopener noreferrer" target="_blank">ROW_NUMBER</a>
<li><a href="https://docs.teradata.com/r/Teradata-VantageTM-SQL%E9%96%A2%E6%95%B0-%E5%BC%8F-%E3%81%8A%E3%82%88%E3%81%B2%E8%BF%B0%E9%83%A8-17.20/%E9%A0%86%E5%BA%8F%E4%BB%98%E3%81%8D%E5%88%86%E6%9E%90%E9%96%A2%E6%95%B0/%E3%82%A6%E3%82%A3%E3%83%B3%E3%83%88%E3%82%A6%E9%9B%86%E7%B4%84%E9%96%A2%E6%95%B0/FIRST_VALUE/LAST_VALUE" rel="noopener noreferrer" target="_blank">FIRST_VALUE/LAST_VALUE</a>
<li><a href="https://docs.teradata.com/r/Teradata-VantageTM-SQL%E3%83%86%E3%83%BC%E3%82%BF%E6%93%8D%E4%BD%9C%E8%A8%80%E8%AA%9E-17.20/Select%E6%96%87/QUALIFY%E5%8F%A5" rel="noopener noreferrer" target="_blank">QUALIFY句</a>
</ul>
"""
en = """
<ul>
<li><a href="https://docs.teradata.com/r/Teradata-VantageTM-SQL-Functions-Expressions-and-Predicates-17.20/Ordered-Analytical/Window-Aggregate-Functions/ROW_NUMBER" rel="noopener noreferrer" target="_blank">ROW_NUMBER</a>
<li><a href="https://docs.teradata.com/r/Teradata-VantageTM-SQL-Functions-Expressions-and-Predicates-17.20/Ordered-Analytical/Window-Aggregate-Functions/FIRST_VALUE/LAST_VALUE" rel="noopener noreferrer" target="_blank">FIRST_VALUE/LAST_VALUE</a>
<li><a href="https://docs.teradata.com/r/Teradata-VantageTM-SQL-Data-Manipulation-Language-17.20/SELECT-Statements/QUALIFY-Clause" rel="noopener noreferrer" target="_blank">QUALIFY Clause</a>
</ul>
"""

# 正誤判定に関する定義
[judgement]
check_shape = true  # クエリ結果の行列数の一致を求めるか
shape = [4, 3]      # 想定されたクエリ結果のサイズ

check_type = false         # クエリ結果の列の型の一致を求めるか
types = [ "int", "str" ]   # 想定されたクエリ結果の変数型

check_value = true  # 想定解との値の一致を求めるか
ordered = false     # クエリ結果の並び順が指定されているかどうか
value_from = "csv"  # 想定結果の指定方法
                    # csv      : 想定結果のCSV文字列を指定
                    # query    : 想定結果を生成するクエリを指定。動的に実行して判定する

csv = """
store_name,purchase_timestamp,customer_name
中央駅前店,2021-10-27 13:00:49+09:00,小嶋 麻理香
空港第２ターミナル店,2022-02-06 15:00:19+09:00,丹羽 有里子
赤坂山アウトレット店,2022-09-05 11:00:48+09:00,杉本 宏文
３番通り店,2021-05-01 10:00:33+09:00,千葉 岳彦
"""

query = """
SELECT DISTINCT
  str.name,
  s.purchase_timestamp,
  c.last_name || '  '|| c.first_name AS customer_name
FROM
  TeraShirt.store_sales AS s
  INNER JOIN TeraShirt.store AS str
    ON s.store_id = str.store_id
  INNER JOIN TeraShirt.customer AS c
    ON s.customer_id = c.customer_id
QUALIFY
  purchase_timestamp = MIN(purchase_timestamp) OVER (PARTITION BY str.name)
"""

check_explain = false   # クエリのExplain結果に関する条件を課すか
explain_should_include = []      # Explanation が含むべきキーワードのリスト
explain_should_not_include = []  # Explanation が含んではいけないキーワードのリスト