# IDはユニークな文字列であれば何でも良いが、なるべくこの形式で（たぶん並べ替えやすいので）
qid = "q0020910"

# タグは文字列の配列。なしでもよい。
# タグには言語の区別はなくても良いだろう。
tags = [
  "geospatial", "math"
]


# カテゴリは必ず１つの文字列。問題の分類に用いる
# 使用できるカテゴリ一覧は別途用意する
[category]
ja = "地理空間情報の分析"
en = "Geospatial Information Analysis"

[title]
ja = """ピタゴラスの定理"""
en = """Pytagolas Theorem"""

[content]
ja = """
点 (0,4), (3,0) を表す幾何情報を作成し、その2点間の距離を計算してください。
ピタゴラスの定理が確認できますか？
"""
en = """
Generate geometry objects representing the points (0,4) and (3,0), and calculate the distance between them.
Is it consistent with the Pythagorean Theorem?
"""


# ヒントなしで
[hint]
ja = """
<ul>
<li><a href="https://docs.teradata.com/r/Teradata-VantageTM-Geospatial-Data-Types/July-2021/ST_Geometry-Constructors-and-Methods/ST_Distance-Method" rel="noopener noreferrer" target="_blank">ST_DISTANCE (マニュアル)</a>
<li><a href="https://ja.wikipedia.org/wiki/%E3%83%94%E3%82%BF%E3%82%B4%E3%83%A9%E3%82%B9%E3%81%AE%E5%AE%9A%E7%90%86" rel="noopener noreferrer" target="_blank">ピタゴラスの定理 (Wikipedia)</a>
</ul>
"""
en = """
<ul>
<li><a href="https://docs.teradata.com/r/Teradata-VantageTM-Geospatial-Data-Types/July-2021/ST_Geometry-Constructors-and-Methods/ST_Distance-Method" rel="noopener noreferrer" target="_blank">ST_DISTANCE (manual)</a>
<li><a href="https://en.wikipedia.org/wiki/Pythagorean_theorem" rel="noopener noreferrer" target="_blank">Pythagorean Theorem (Wikipedia)</a>
</ul>
"""


# 正誤判定に関する定義
[judgement]
check_shape = false         # クエリ結果の行列数の一致を求めるか
shape = [1, 1]             # 想定されたクエリ結果のサイズ

check_type = false          # クエリ結果の列の型の一致を求めるか
#types = [ "int" ]          # 想定されたクエリ結果の変数型

check_value = true         # 想定解との値の一致を求めるか
ordered = true             # クエリ結果の並び順が指定されているかどうか
value_from = "csv"       # 想定結果の指定方法
                           # csv      : 想定結果のCSV文字列を指定
                           # query    : 想定結果を生成するクエリを指定。動的に実行して判定する
csv = """
answer
5.00
"""

query = """
WITH tmp AS (
  SELECT
    NEW ST_Geometry('ST_Point', 0, 4) AS x,
    NEW ST_Geometry('ST_Point', 3, 0) AS y
)
SELECT x.ST_DISTANCE(y) AS len FROM tmp
"""

check_explain = false