# IDはユニークな文字列であれば何でも良いが、なるべくこの形式で（たぶん並べ替えやすいので）
qid = "q00000121"

# タグは文字列の配列。なしでもよい。
# タグには言語の区別はなくても良いだろう。
tags = [
  "date",
  "sort"
]


# カテゴリは必ず１つの文字列。問題の分類に用いる
# 使用できるカテゴリ一覧は別途用意する
[category]
ja = "SQL/Teradata 基礎"
en = "SQL/Teradata Basic"

[title]
ja = "最近登録した顧客"
en = "Customers who recently registered"

[content]
ja = """<em>TeraShirt.customer</em> テーブルには、TeraShirt社の顧客の情報が格納されています。
登録日の新しい順に、最近登録した5人の顧客を表示してください。
出力内容は、姓、名及び登録日としてください。
"""
en = """<em>TeraShirt.customer</em> table stores the information of customers of the TeraShirt company.
Show latest 5 customers sorted by the register date in descending order.
The output should contain the last name, first name and register date.
"""


[hint]
ja = ""
en = ""


[references]
ja = ""
en = ""


# 正誤判定に関する定義
[judgement]
check_shape = true         # クエリ結果の行列数の一致を求めるか
shape = [5, 3]             # 想定されたクエリ結果のサイズ

check_type = true          # クエリ結果の列の型の一致を求めるか
types = [ "str", "str", "str" ]         # 想定されたクエリ結果の変数型

check_value = true         # 想定解との値の一致を求めるか
ordered = true             # クエリ結果の並び順が指定されているかどうか
value_from = "csv"         # 想定結果の指定方法
                           # csv      : 想定結果のCSV文字列を指定
                           # query    : 想定結果を生成するクエリを指定。動的に実行して判定する
csv = """
last_name,first_name,register_date
山本,雄貴,2022-12-20
園田,明子,2022-12-18
片山,早苗,2022-12-14
小松,春奈,2022-11-19
藤井,和弘,2022-11-15
"""
query = """
SELECT
  last_name, first_name, register_date
FROM
  TeraShirt.customer
QUALIFY
  RANK() OVER (ORDER BY register_date DESC) <= 5
ORDER BY 3 DESC
"""

check_explain = false