# IDはユニークな文字列であれば何でも良いが、なるべくこの形式で（たぶん並べ替えやすいので）
qid = "q00000010"   # 中途半端なIDだが、最初の問題としては変わり種なので、若い番号を開けておく。

# タグは文字列の配列。なしでもよい。
# タグには言語の区別はなくても良いだろう。
tags = [
  "teradata-specific"
]


# カテゴリは必ず１つの文字列。問題の分類に用いる
# 使用できるカテゴリ一覧は別途用意する
[category]
ja = "SQL/Teradata 基礎"
en = "SQL/Teradata Basic"

[title]
ja = """Teradata セッション番号"""
en = """Teradata Session Number"""

[content]
ja = """Teradataデータベースへ接続すると、1つのセッション番号が割り振られます。そのセッション番号を表示してください。
<br />
セッション番号は、1つの整数値です。
"""
en = """When you connect to the teradata database, you will be assigned a session number. <br/>
Show the session number of the current teradata database connection. <br/>
Note that the session number is a single integer value.
"""


# ヒントなしで
[hint]
ja = ""
en = ""


# 参考文献なしで
[references]
ja = ""
en = ""


# 正誤判定に関する定義
[judgement]
check_shape = true         # クエリ結果の行列数の一致を求めるか
shape = [1, 1]             # 想定されたクエリ結果のサイズ

check_type = true          # クエリ結果の列の型の一致を求めるか
types = [ "int" ]          # 想定されたクエリ結果の変数型

check_value = true         # 想定解との値の一致を求めるか
ordered = true             # クエリ結果の並び順が指定されているかどうか
value_from = "query"       # 想定結果の指定方法
                           # csv      : 想定結果のCSV文字列を指定
                           # query    : 想定結果を生成するクエリを指定。動的に実行して判定する
#csv = 
query = """SELECT SESSION AS session_number"""
# セッション値は毎回異なるので、動的にクエリで解を取得する

check_explain = false