# IDはユニークな文字列であれば何でも良いが、なるべくこの形式で（たぶん並べ替えやすいので）
qid = "q00000113"

# タグは文字列の配列。なしでもよい。
# タグには言語の区別はなくても良いだろう。
tags = [
  "date",
  "set-operator"
]


# カテゴリは必ず１つの文字列。問題の分類に用いる
# 使用できるカテゴリ一覧は別途用意する
[category]
ja = "SQL/Teradata 基礎"
en = "SQL/Teradata Basic"

[title]
ja = "1989/08/10生まれの人"
en = "Someone whose birthday is August 10th, 1989"

[content]
ja = """<em>TeraShirt.customer</em> テーブルには、TeraShirt社の顧客情報が、
また <em>TeraShirt.employee</em> テーブルには、TeraShirt社の従業員情報が格納されています。<br />
全ての顧客と従業員のうち、1989/08/10生まれの人の姓と名を表示してください。
"""
en = """<em>TeraShirt.customer</em> table stores the information of customers of the TeraShirt company, and
<em>TeraShirt.employee</em> table stores the information of its employees.<br />
Of all customers and employees, show the last name and first name of someone whose birthday is August 10th, 1989.
"""


[hint]
ja = ""
en = ""


[references]
ja = ""
en = ""


# 正誤判定に関する定義
[judgement]
check_shape = true         # クエリ結果の行列数の一致を求めるか
shape = [2, 2]             # 想定されたクエリ結果のサイズ

check_type = true          # クエリ結果の列の型の一致を求めるか
types = [ "str", "str" ]         # 想定されたクエリ結果の変数型

check_value = true         # 想定解との値の一致を求めるか
ordered = false            # クエリ結果の並び順が指定されているかどうか
value_from = "csv"         # 想定結果の指定方法
                           # csv      : 想定結果のCSV文字列を指定
                           # query    : 想定結果を生成するクエリを指定。動的に実行して判定する
csv = """
last_name,first_name
井上,栞
"""

query = """
SELECT
  last_name, first_name
FROM
  TeraShirt.employee
WHERE
  birthday = DATE'1989-08-10'
"""

check_explain = false