# これは問題定義のテンプレートファイルです。実際には問題文に含まれません。
# ファイル名はある程度概要がわかるものをつけます。

# IDはユニークな文字列であれば何でも良いが、なるべくこの形式で（たぶん並べ替えやすいので）
qid = "q00003000"

# タグは文字列の配列。なしでもよい。
# タグには言語の区別はなくても良いだろう。
tags = [
  "teradata-specific",
  "skewness"
]


# カテゴリは必ず１つの文字列。問題の分類に用いる
# 使用できるカテゴリ一覧は別途用意する
# 現在想定しているものは以下（これに含まれないものをアプリ上で表示されないようになっているので、別途アプリ側で追加する必要がある）
#  ja: ("SQL/Teradata 基礎", "SQL/Teradata 中級", "地理空間情報の分析", "時系列情報の分析")
#  en: ("SQL/Teradata Basic", "SQL/Teradata Intermediate", "Geospatial Information Analysis", "Time-series Data")
[category]
ja = "SQL/Teradata 中級"
en = "SQL/Teradata Intermediate"

[title]
ja = """
テーブルデータの偏り (Skewness)
"""
en = """
Skewness of table data
"""

[content]
ja = """
テーブルデータは1つ以上のAMPに分散して保持されています。一般に、データが偏りなく均等に分散しているほど、計算処理の効率が良くなります。
Skewness は、データの偏りを表す指標で、次のように定義されます：

<pre>
Skewness = 1 - AMP容量の平均値 / AMP容量の最大値
</pre>

仮にすべてのAMPに同じ容量のデータが保持されていれば、平均値と最大値は一致するため、Skewness はゼロになります。
また、データが10個のAMPのうちの1つに集中している場合、平均値は最大値の1/10 になるため、Skewness は 0.9 となります。
なお、Skewnessは上の定義に100をかけてパーセント表記されることが多いです。

<em>TeraShirt.store</em> と <em>TeraShirt.store_sales</em> のSkewnessをパーセント表記で計算してください。
結果にはデータベース名、テーブル名、Skewnessを表示してください。

【Optional】また、Skewnessの値が一方のテーブルで高めに出るのか、考えてみてください。
"""
en = """
Table data are distributed across clusters in the teradata system.
In general, the computation becomes efficient when data are distributed uniformly.
The skewness is a measure that represents the degree of data concentration.

<pre>
Skewness = 1 - Average size across AMPs / Maximum size among AMPs
</pre>

If all AMPs have the equal size of data, then the average equals the maximum, and hence the skewness is zero.
If data are concentrated to one of ten AMPs, then the average will become 1/10 of the maximum, so the skewness is 0.9.
Note that skewness is often shown in percent scale, which is the above definition multiplied by 100.

Calculate the skewness of <em>TeraShirt.store</em> and <em>TeraShirt.store_sales</em> in percent scale.
Include database name, table name and skewness in the result set.

[Optional] Think about why the skewness is larger for one of the tables.
"""

# ヒントが不要なら空文字列にする
[hint]
ja = """
テーブル容量は、<em>DBC.TableSizeV</em> に保持されています。
"""
en = """
Disk spaces are stored in <em>DBC.TableSizeV</em>.
"""

# 参考文献、ウェブサイト (HTMLコードを直接書く)
# 不要なら空文字列にする
[references]
ja = """
"""
en = """
"""

# 正誤判定に関する定義
[judgement]
check_shape = false  # クエリ結果の行列数の一致を求めるか
shape = [1, 2]      # 想定されたクエリ結果のサイズ

check_type = false          # クエリ結果の列の型の一致を求めるか
types = [ "int", "str" ]   # 想定されたクエリ結果の変数型

check_value = true  # 想定解との値の一致を求めるか
ordered = false     # クエリ結果の並び順が指定されているかどうか
value_from = "query"  # 想定結果の指定方法
                    # csv      : 想定結果のCSV文字列を指定
                    # query    : 想定結果を生成するクエリを指定。動的に実行して判定する
# csv = """
# x,y
# 1,test
# """

# value_from=csvなので、これは不要だが、例として示す
# 実際には、定義しないのが良い
query = """
SELECT
  databaseName, tableName, 
  (1 - AVG(currentPerm) / MAX(currentPerm)) * 100 AS skewness
FROM
  dbc.TableSizeV
WHERE
  databaseName = 'terashirt' AND tableName IN ('store', 'store_sales')
GROUP BY 1,2
"""

check_explain = false   # クエリのExplain結果に関する条件を課すか
explain_should_include = []      # Explanation が含むべきキーワードのリスト
explain_should_not_include = []  # Explanation が含んではいけないキーワードのリスト